class DouYu_barrage_generate:
    
    def __init__(self):
        self.barrage_list = []
        self.barrage_default = ['\ufeff[Script Info]\n', '; Script generated by Aegisub 3.2.2\n', '; http://www.aegisub.org/\n', 'Synch Point: 1\n', 'ScriptType: v4.00+\n', 'PlayResX: 0\n', 'PlayResY: 0\n', 'WrapStyle: 0\n', 'ScaledBorderAndShadow: no\n', '\n', '[Aegisub Project Garbage]\n', 'Last Style Storage: Default\n', 'Video Zoom Percent: 0.875000\n', 'Active Line: 6\n', 'Video Position: 352\n', '\n', '[V4+ Styles]\n', 'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n', 'Style: Default,微软雅黑,15,&H00FFFFFF,&HF0000000,&H00000000,&H32000000,0,0,0,0,100,100,0,0,1,2,1,2,5,5,2,134\n', '\n', '[Events]\n', 'Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n'] 
        
        self.barrage_positions = [15.0, 30.0, 45.0, 60.0, 75.0, 90.0, 105.0]
        self.barrage_gates     = [1,    1,    1,    1,    1,    1,    1    ]
        self.barrage_time      = [None, None, None, None, None, None, None ]

    def load_barrage(self, filename):
        f = open(filename+".txt", mode='r')
        for line in f.readlines():
            line = line.strip()
            each_barrage = line.split("&&&")
            self.barrage_list.append(each_barrage)
        def take_first(elem):
            parts = elem[0].split(':')
            return int(parts[0])       
        self.barrage_list.reverse()
        self.barrage_list.sort(key = take_first)  
        f.close()
        
        
    def generate_each_barrage(self, barrage):
        index = None
        try:
            index = self.barrage_gates.index(1)
        except:
            index = self.barrage_time.index(min(self.barrage_time))
        position = self.barrage_positions[index]
        self.barrage_gates[index] = 0
        barrage_time_part = barrage[0].split(':')
        hour = 0
        minute = int(barrage_time_part[0])
        second = int(barrage_time_part[1])
        if minute // 60 != 0:
            hour = minute // 60
            minute = minute % 60
        barrage_start_time = str(hour)+":"+str(minute)+":"+str(second)+".00"
        barrage_end_time = str(hour)+":"+str(minute)+":"+str(second+20)+".00"
        barrage_position = "{\pos(383,"+str(position)+")}"
        barrage_content = barrage[1]
        final_barrage = "Dialogue: 0,"+str(barrage_start_time)+","+str(barrage_end_time)+\
            ",*Default,NTP,0,0,0,banner;25;0;0,"+str(barrage_position)+str(barrage_content)+"\n"
        count_time_as_second = hour*3600 + minute*60 + second
        self.barrage_time[index] = count_time_as_second
        for i in range(len(self.barrage_time)):
            if self.barrage_time[i]!=None and count_time_as_second >= self.barrage_time[i] + 2:
                self.barrage_time[i] = None
                self.barrage_gates[i] = 1
        print(final_barrage)
        return final_barrage
        
        
    def generate_barrage(self, filename):
        #Dialogue: 0,0:00:01.27,0:00:15.00,*Default,NTP,0,0,0,banner;15;0;0,{\pos(383,15.0)}弗雷德  住手
        #Dialogue: 0,0:00:02.11,0:00:55.07,*Default,NTP,0,0,0,banner;15;0;0,{\pos(383,30.0)}《侍女的故事》前情提要
        #Dialogue: 0,0:00:04.07,0:00:55.07,*Default,NTP,0,0,0,banner;15;0;0,{\pos(383,45.0)}是你让他们对塞丽娜那么做的
        #Dialogue: 0,0:00:06.07,0:00:55.19,*Default,NTP,0,0,0,banner;15;0;0,{\pos(383,60.0)}我们都有各自的角色要扮演
        #Dialogue: 0,0:00:08.20,0:00:55.20,*Default,NTP,0,0,0,banner;15;0;0,{\pos(383,75.0)}需要提醒塞丽娜别忘记她的角色
        #Dialogue: 0,0:00:10.20,0:00:55.74,*Default,NTP,0,0,0,banner;15;0;0,{\pos(383,90.0)}你试着找过我么
        #Dialogue: 0,0:00:11.74,0:00:55.24,*Default,NTP,0,0,0,banner;15;0;0,{\pos(383,105.0)}我非常努力地找        
        f = open(filename+".ass", mode='w',encoding='UTF-8')
        f.writelines(self.barrage_default)
        for barrage in self.barrage_list:
            f.write(self.generate_each_barrage(barrage))
        f.close()
            
        
    def run(self):
        self.load_barrage("怀旧服beta 60937 2019-06-05 20点场 弹幕")
        self.generate_barrage("怀旧服beta 60937 2019-06-05 20点场 弹幕")     
        print("完成")

if __name__=='__main__':
    douYu_barrage_generate = DouYu_barrage_generate()
    douYu_barrage_generate.run()        
